- name: Installing Prometheus on Ubuntu
  apt: 
     name: prometheus
     state: latest
     update_cache: yes
  when: ansible_distribution == "Ubuntu"


- name: Installing snapd on Centos
  dnf:
    name:
        - snapd
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: enabling sockets
  tags: snapd,centos
  command: systemctl enable --now snapd.socket
  when: ansible_distribution == "CentOS"

- name: installing prometheus using snapd
  tags: centos, prometheus
  command: snap install prometheus  --classic
  when: ansible_distribution == "CentOS"

# - name: 

#- name: starting prometheus on ubuntu 
#  tags: prometheus
 # command: systemctl start --now  prometheus
 # when: ansible_distribution == "Ubuntu"

# - name: enabling prometheus on ubuntu 
 # tags: prometheus
  #command: systemctl start --now prometheus
